import turtle
def initials():
    window = turtle.Screen()
    window.bgcolor("black")
    pg = turtle.Turtle()
    pg.color("white")
    pg.speed(4)
    pg.left(90)
    pg.fd(200)
    pg.right(90)
    pg.circle(-50,180)
    pg.up()
    pg.goto(165,200)
    pg.down()
   # pg.left(180)
    pg.circle(85,180)
    pg.circle(75,90)
    pg.left(90)
    pg.fd(60)
    pg.back(90)   
    pg.right(270)
    pg.fd(100)
    window.exitonclick()

initials()
